import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

export const LANGUAGE_STORAGE_KEY = 'codemaster_language'

const resources = {
  en: { translation: {
    header: { home: 'Go to CodeMaster home', subtitle: 'Premium EdTech', features: 'Features', platform: 'Platform', start: 'Start', startLearning: 'Start learning', themeLight: 'Light mode', themeDark: 'Dark mode', language: 'Language' },
    landing: {
      featuresKicker: 'Platform features',
      featuresTitle: 'Built for professional engineering momentum.',
      featuresSubtitle: 'Deep IDE integration, AI review, and PARA organization turn lessons into production-grade habits.',
      features: {
        ide: { title: 'Professional IDE Workflow', description: 'Move from lesson to local VS Code with deep links and real engineering context.', preview: 'Preview: click a task → vscode://file opens the exact practice file.' },
        mentor: { title: 'AI Mentorship', description: 'Get senior-level architectural hints, review framing, and PARA guidance without direct spoilers.', preview: 'Preview: Gemini reviews code, returns stars, and writes inline mentor comments.' },
        paths: { title: 'Engineering learning paths', description: 'Progress through theory, practice, and checklists with professional sequencing.', preview: 'Preview: Lesson 2 unlocks only after Lesson 1 reaches a 4/5 average.' },
        scoring: { title: 'Code quality scoring', description: 'Receive 1-5 star feedback for clean code, performance, and logic.', preview: 'Preview: score evolves from Beginner to Master using progress and AI averages.' },
        split: { title: 'Task & Solution split view', description: 'Read focused Markdown on the left and execute practice decisions on the right.', preview: 'Preview: theory stays visible while you solve Basic, Intermediate, and Pro tasks.' },
        brain: { title: 'Second Brain organization', description: 'Use PARA to connect projects, areas, resources, and archives inside every lesson.', preview: 'Preview: reusable patterns move from Projects into Resources after verification.' }
      }
    },
    dashboard: { title: 'Dashboard', path: 'Path', level: 'Level', score: 'Score', certificateName: 'Certificate name', certificatePlaceholder: 'Example: Alex Smith', continue: 'Continue', changePath: 'Change path', progress: 'Progress', points: 'Points', achievements: 'Achievements', modules: 'modules', pointsHint: 'Start completing tasks to earn points', refresh: 'Refresh', performanceHub: 'Performance Hub', analytics: 'Engineering analytics', telemetry: 'Trading-style growth, daily streaks, and AI-score telemetry', badges: { title: 'Badges', clean: 'Clean Code', velocity: 'Velocity', mentor: 'Mentor Signal', architect: 'Architect' }, analyticsLabels: { avgQuality: 'Avg Quality', linesVerified: 'Lines Verified', activeDeadlines: 'Active Deadlines', skillGrowth: 'Skill Growth Chart', skillGrowthSub: 'Engineering Level momentum', live: 'LIVE', activityHeatmap: 'Activity Heatmap', heatmapSub: 'Daily coding streak signal', less: 'Less', more: 'More' }, modulesSection: { title: 'Modules', openPlan: 'Open plan →', done: 'Done', inProgress: 'In progress', hours: 'h', tasks: 'tasks', noPath: 'Select a learning path to view modules.' }, achievementsSection: { title: 'Achievements', empty: 'No achievements yet. Click Refresh after completing modules.' }, certificateSection: { title: 'Certificate', description: 'Certificate becomes available after completing all modules of the selected path.', export: 'Export certificate', fallbackName: 'Student' } },
    paths: {
      title: 'Choose your learning path', subtitle: 'Your direction defines topics, tasks, and your future certificate.', assessment: 'Take level test', roadmap: 'Interactive roadmap tree', hours: 'h', topics: 'topics', deadline: 'Deadline', progress: 'Progress', select: 'Choose path', footer: 'Not sure? Start with the level test and it will help you choose an entry point.', progressLabel: 'Progress {{progress}}%', moreTopics: '+{{count}}',
      levels: { beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced', master: 'Master' },
      tracks: {
        frontend: { title: 'Frontend Development', description: 'Master modern frontend technologies including HTML, CSS, JavaScript, and popular frameworks like React, Vue, and Angular' },
        backend: { title: 'Backend Development', description: 'Learn server-side programming with Node.js, Python, Java, and C#. Build robust APIs and database systems' },
        mobile: { title: 'Mobile Development', description: 'Create cross-platform and native mobile applications with React Native, Flutter, Swift, and Kotlin' },
        'data-science': { title: 'Data Science', description: 'Dive into data analysis, machine learning, and statistical programming with Python, R, and SQL' }
      }
    },
    lesson: { notFound: 'Lesson not found', chooseLesson: 'Choose a lesson from the learning plan to continue.', backToPlan: 'Back to plan', plan: 'Plan', resources: 'PARA lesson resources', kicker: '{{hours}} h reading and practice', showcase: 'Showcase Code', taskSolution: 'Task & Solution', practiceTasks: '3 Practice Tasks', instruction: 'Open the dedicated local task file, solve each exercise, and let the Senior DRM Lead judge your average score.', deadline: 'Smart deadline ({{hours}}h): {{time}}', task: 'Task {{index}}', solveInVSCode: 'Solve in VS Code', verifying: 'Verifying…', verifyTask: 'Verify task', accepted: 'Mastery signal accepted', iteration: 'Needs another iteration', reviewComments: 'Review Comments', terminal: 'verify-terminal', terminalLogs: ['Scanning syntax...', 'Applying Clean Code heuristics...', 'Consulting Senior AI...'], average: 'Average AI-score: {{score}}/5', approved: 'Senior DRM Lead approved progression.', rule: '4/5 Rule active: verify all tasks until the average is at least 4.0.', completed: 'Completed', complete: 'Complete & unlock next', locked: 'Locked until 4/5 average', mentor: 'AI Senior Mentor', thinking: 'Thinking...', mentorText: 'Senior DRM Lead is evaluating all three tasks, architecture signals, and whether you can progress.', lesson: 'Lesson', verdict: 'Verdict', progressionApproved: 'Progression approved', lockedByRule: 'Locked by 4/5 Rule', averageScore: 'Average score', acrossTasks: '{{score}}/5 across {{count}} tasks', paraTip: 'PARA tip', paraTipText: 'Promote reusable patterns from Projects into Resources after verification.', para: { projects: 'Projects', areas: 'Areas', resources: 'Resources', archives: 'Archives', heading: 'PARA' } },
    learningPlan: { title: 'Learning Plan', pathLabel: 'Path', done: 'Done', progress: 'Progress', totalModules: 'Total modules', hoursEstimate: 'Hours (estimate)', level: 'Level', modulesTitle: 'Modules', hours: 'h', aiScore: 'AI score', requires: 'Requires', btnDone: 'Done', btnLocked: 'Locked', btnStart: 'Start', ruleHint: '4/5 Rule: first get average AI-score ≥ 4.0 in lesson {{lessons}}', changePath: '← Change path', dashboard: 'Dashboard →', levels: { junior: 'Junior', mid: 'Mid', senior: 'Senior', beginner: 'Beginner', intermediate: 'Intermediate', advanced: 'Advanced', master: 'Master' }, modules: { 'lesson-1-philosophy-career': { title: 'Lesson 1: {{track}} Philosophy & Career', description: 'Understand the why, industry context, and career roadmap for {{track}}.' }, 'lesson-2-core-foundations': { title: '{{track}} Core Foundations', description: 'Build production-grade foundations with {{stack}}.' }, 'lesson-3-professional-workflow': { title: '{{track}} Professional Workflow', description: 'Practice professional review, refactoring, and delivery habits.' } } },
    assessment: { title: 'Knowledge Assessment', questionOf: 'Question {{current}} of {{total}}', timeLeft: 'Time left', difficulty: 'Difficulty', category: 'Category', back: 'Back', next: 'Next', finish: 'Finish', completed: 'Test Completed', completedSub: 'We assessed your level and picked a starting point.', correctAnswers: 'Correct answers', level: 'Level', recommendations: 'Recommendations', strengths: 'Strengths', improve: 'Areas to improve', goToLearning: 'Go to learning', levels: { senior: 'Senior', mid: 'Mid', junior: 'Junior' }, descriptions: { senior: 'Advanced level', mid: 'Solid foundation', junior: 'Starting level' }, recs: { senior: 'Start with advanced topics and real projects.', mid: 'Strengthen your knowledge with practice and move to harder tasks.', junior: 'Start with the basics and practice regularly.' }, strengthItems: { goodBase: 'Good knowledge base', logicOk: 'Decent logical thinking', readyToLearn: 'Ready to learn' }, improveItems: { advanced: 'Advanced topics', basics: 'Fundamentals', morePractice: 'More practice' } }
  } },
  ru: { translation: {
    header: { home: 'На главную CodeMaster', subtitle: 'Премиум EdTech', features: 'Функции', platform: 'Платформа', start: 'Старт', startLearning: 'Начать обучение', themeLight: 'Светлая тема', themeDark: 'Тёмная тема', language: 'Язык' },
    landing: {
      featuresKicker: 'Возможности платформы',
      featuresTitle: 'Создано для профессионального инженерного темпа.',
      featuresSubtitle: 'Глубокая интеграция с IDE, AI-ревью и PARA превращают уроки в продакшен-привычки.',
      features: {
        ide: { title: 'Профессиональный IDE-процесс', description: 'Переходи из урока в локальный VS Code через deep links и реальный инженерный контекст.', preview: 'Превью: нажми задачу → vscode://file откроет точный файл практики.' },
        mentor: { title: 'AI-наставник', description: 'Получай архитектурные подсказки senior-уровня, формат ревью и PARA-направление без прямых спойлеров.', preview: 'Превью: Gemini проверяет код, возвращает звёзды и inline-комментарии ментора.' },
        paths: { title: 'Инженерные треки обучения', description: 'Проходи теорию, практику и чеклисты в профессиональной последовательности.', preview: 'Превью: Урок 2 откроется только после среднего 4/5 за Урок 1.' },
        scoring: { title: 'Оценка качества кода', description: 'Получай оценку 1–5 звёзд за чистоту кода, производительность и логику.', preview: 'Превью: уровень растёт от Новичка до Мастера по прогрессу и AI-среднему.' },
        split: { title: 'Разделение задания и решения', description: 'Читай сфокусированный Markdown слева и выполняй практические решения справа.', preview: 'Превью: теория остаётся видимой, пока ты решаешь Basic, Intermediate и Pro задачи.' },
        brain: { title: 'Организация Second Brain', description: 'Используй PARA, чтобы связывать проекты, зоны ответственности, ресурсы и архивы внутри каждого урока.', preview: 'Превью: переиспользуемые паттерны переходят из Projects в Resources после проверки.' }
      }
    },
    dashboard: { title: 'Панель', path: 'Путь', level: 'Уровень', score: 'Балл', certificateName: 'Имя для сертификата', certificatePlaceholder: 'Например: Иван Иванов', continue: 'Продолжить', changePath: 'Сменить путь', progress: 'Прогресс', points: 'Очки', achievements: 'Достижения', modules: 'модулей', pointsHint: 'Начни выполнять задания, чтобы зарабатывать очки', refresh: 'Обновить', performanceHub: 'Центр эффективности', analytics: 'Инженерная аналитика', telemetry: 'Рост в стиле трейдинга, ежедневные серии и AI-score телеметрия', badges: { title: 'Бейджи', clean: 'Чистый код', velocity: 'Темп', mentor: 'Сигнал ментора', architect: 'Архитектор' }, analyticsLabels: { avgQuality: 'Среднее качество', linesVerified: 'Строк проверено', activeDeadlines: 'Активные дедлайны', skillGrowth: 'График роста', skillGrowthSub: 'Динамика инженерного уровня', live: 'LIVE', activityHeatmap: 'Активность', heatmapSub: 'Ежедневная серия', less: 'Меньше', more: 'Больше' }, modulesSection: { title: 'Модули', openPlan: 'Открыть план →', done: 'Готово', inProgress: 'В процессе', hours: 'ч', tasks: 'заданий', noPath: 'Выбери путь обучения, чтобы увидеть модули.' }, achievementsSection: { title: 'Достижения', empty: 'Пока нет достижений. Нажми «Обновить» после прохождения модулей.' }, certificateSection: { title: 'Сертификат', description: 'Сертификат становится доступен после завершения всех модулей выбранного пути.', export: 'Экспортировать сертификат', fallbackName: 'Ученик' } },
    paths: {
      title: 'Выбери путь обучения', subtitle: 'Направление определит темы, задания и будущий сертификат.', assessment: 'Пройти тест уровня', roadmap: 'Интерактивная дорожная карта', hours: 'ч', topics: 'тем', deadline: 'Дедлайн', progress: 'Прогресс', select: 'Выбрать путь', footer: 'Если не уверен — начни с теста уровня, он поможет выбрать точку входа.', progressLabel: 'Прогресс {{progress}}%', moreTopics: '+{{count}}',
      levels: { beginner: 'Новичок', intermediate: 'Средний', advanced: 'Продвинутый', master: 'Мастер' },
      tracks: {
        frontend: { title: 'Frontend-разработка', description: 'Освой современные frontend-технологии: HTML, CSS, JavaScript и популярные фреймворки React, Vue и Angular' },
        backend: { title: 'Backend-разработка', description: 'Изучи серверную разработку на Node.js, Python, Java и C#. Создавай надёжные API и базы данных' },
        mobile: { title: 'Мобильная разработка', description: 'Создавай кроссплатформенные и нативные мобильные приложения на React Native, Flutter, Swift и Kotlin' },
        'data-science': { title: 'Наука о данных', description: 'Погрузись в анализ данных, машинное обучение и статистическое программирование на Python, R и SQL' }
      }
    },
    lesson: { notFound: 'Урок не найден', chooseLesson: 'Выбери урок из плана обучения, чтобы продолжить.', backToPlan: 'Назад к плану', plan: 'План', resources: 'PARA ресурсы урока', kicker: '{{hours}} ч чтения и практики', showcase: 'Демо-код', taskSolution: 'Задание и решение', practiceTasks: '3 практических задания', instruction: 'Открой локальный файл задания, реши каждое упражнение и дай Senior DRM Lead оценить средний балл.', deadline: 'Умный дедлайн ({{hours}}ч): {{time}}', task: 'Задание {{index}}', solveInVSCode: 'Решить в VS Code', verifying: 'Проверка…', verifyTask: 'Проверить задание', accepted: 'Сигнал мастерства принят', iteration: 'Нужна ещё итерация', reviewComments: 'Комментарии ревью', terminal: 'verify-terminal', terminalLogs: ['Сканирование синтаксиса...', 'Применение Clean Code эвристик...', 'Консультация с Senior AI...'], average: 'Средний AI-score: {{score}}/5', approved: 'Senior DRM Lead одобрил переход дальше.', rule: 'Правило 4/5 активно: проверь все задания, пока средний балл не станет минимум 4.0.', completed: 'Завершено', complete: 'Завершить и открыть следующий', locked: 'Закрыто до среднего 4/5', mentor: 'AI Senior Mentor', thinking: 'Думаю...', mentorText: 'Senior DRM Lead оценивает все три задания, архитектурные сигналы и готовность идти дальше.', lesson: 'Урок', verdict: 'Вердикт', progressionApproved: 'Переход одобрен', lockedByRule: 'Закрыто правилом 4/5', averageScore: 'Средний балл', acrossTasks: '{{score}}/5 по {{count}} заданиям', paraTip: 'PARA совет', paraTipText: 'После проверки переноси переиспользуемые паттерны из Projects в Resources.', para: { projects: 'Проекты', areas: 'Зоны', resources: 'Ресурсы', archives: 'Архивы', heading: 'PARA' } },
    learningPlan: { title: 'План обучения', pathLabel: 'Путь', done: 'Готово', progress: 'Прогресс', totalModules: 'Всего модулей', hoursEstimate: 'Часов (оценка)', level: 'Уровень', modulesTitle: 'Модули', hours: 'ч', aiScore: 'AI score', requires: 'Нужно', btnDone: 'Готово', btnLocked: 'Закрыто', btnStart: 'Начать', ruleHint: '4/5 Rule: сначала получи средний AI-score ≥ 4.0 в уроке {{lessons}}', changePath: '← Сменить путь', dashboard: 'Dashboard →', levels: { junior: 'Junior', mid: 'Mid', senior: 'Senior', beginner: 'Новичок', intermediate: 'Средний', advanced: 'Продвинутый', master: 'Мастер' }, modules: { 'lesson-1-philosophy-career': { title: 'Урок 1: Философия и карьера в {{track}}', description: 'Пойми зачем это нужно, индустриальный контекст и карьерную дорожную карту для {{track}}.' }, 'lesson-2-core-foundations': { title: 'Базовые основы {{track}}', description: 'Построй продакшен-уровень основ с {{stack}}.' }, 'lesson-3-professional-workflow': { title: 'Профессиональный workflow в {{track}}', description: 'Практикуй профессиональный review, рефакторинг и привычки поставки.' } } },
    assessment: { title: 'Оценка знаний', questionOf: 'Вопрос {{current}} из {{total}}', timeLeft: 'Осталось времени', difficulty: 'Сложность', category: 'Категория', back: 'Назад', next: 'Далее', finish: 'Завершить', completed: 'Тест завершён', completedSub: 'Мы оценили текущий уровень и подобрали старт.', correctAnswers: 'Верных ответов', level: 'Уровень', recommendations: 'Рекомендации', strengths: 'Сильные стороны', improve: 'Что подтянуть', goToLearning: 'Перейти к обучению', levels: { senior: 'Senior', mid: 'Mid', junior: 'Junior' }, descriptions: { senior: 'Продвинутый уровень', mid: 'Уверенная база', junior: 'Стартовый уровень' }, recs: { senior: 'Начни с продвинутых тем и реальных проектов.', mid: 'Закрепи знания на практике и переходи к более сложным заданиям.', junior: 'Начни с основ и регулярно практикуйся.' }, strengthItems: { goodBase: 'Хорошая база', logicOk: 'Неплохое понимание логики', readyToLearn: 'Готовность учиться' }, improveItems: { advanced: 'Продвинутые темы', basics: 'Основы', morePractice: 'Больше практики' } }
  } },
  uz: { translation: {
    header: { home: 'CodeMaster bosh sahifasiga oʻtish', subtitle: 'Premium EdTech', features: 'Imkoniyatlar', platform: 'Platforma', start: 'Boshlash', startLearning: 'Oʻqishni boshlash', themeLight: 'Yorugʻ rejim', themeDark: 'Tungi rejim', language: 'Til' },
    landing: {
      featuresKicker: 'Platforma imkoniyatlari',
      featuresTitle: 'Professional muhandislik surʻati uchun yaratilgan.',
      featuresSubtitle: 'Chuqur IDE integratsiyasi, AI review va PARA darslarni production darajasidagi odatlarga aylantiradi.',
      features: {
        ide: { title: 'Professional IDE jarayoni', description: 'Darsdan lokal VS Codeʻga deep link va real muhandislik konteksti bilan oʻting.', preview: 'Preview: topshiriqni bosing → vscode://file aniq amaliyot faylini ochadi.' },
        mentor: { title: 'AI mentorlik', description: 'Toʻgʻridan-toʻgʻri javobsiz senior darajadagi arxitektura maslahatlari, review yoʻnalishi va PARA koʻrsatmalarini oling.', preview: 'Preview: Gemini kodni tekshiradi, yulduzlar va inline mentor izohlarini qaytaradi.' },
        paths: { title: 'Muhandislik oʻquv yoʻlari', description: 'Nazariya, amaliyot va checklistlarni professional ketma-ketlikda bajaring.', preview: 'Preview: 2-dars faqat 1-dars oʻrtachasi 4/5 boʻlgandan keyin ochiladi.' },
        scoring: { title: 'Kod sifati baholash', description: 'Clean code, performance va mantiq uchun 1–5 yulduzli baho oling.', preview: 'Preview: daraja progress va AI oʻrtachasi orqali Boshlovchidan Mastergacha oʻsadi.' },
        split: { title: 'Topshiriq va yechim split-view', description: 'Chapda aniq Markdownʻni oʻqing, oʻngda amaliy qarorlarni bajaring.', preview: 'Preview: Basic, Intermediate va Pro topshiriqlarini yechishda nazariya koʻrinib turadi.' },
        brain: { title: 'Second Brain tashkiloti', description: 'Har bir darsda loyihalar, sohalar, resurslar va arxivlarni PARA orqali bogʻlang.', preview: 'Preview: qayta ishlatiladigan patternlar tekshiruvdan keyin Projectsʻdan Resourcesʻga oʻtadi.' }
      }
    },
    dashboard: { title: 'Dashboard', path: 'Yoʻl', level: 'Daraja', score: 'Ball', certificateName: 'Sertifikat uchun ism', certificatePlaceholder: 'Masalan: Ali Karimov', continue: 'Davom etish', changePath: 'Yoʻlni almashtirish', progress: 'Progress', points: 'Ballar', achievements: 'Yutuqlar', modules: 'modul', pointsHint: 'Ball olish uchun topshiriqlarni bajarishni boshlang', refresh: 'Yangilash', performanceHub: 'Samaradorlik markazi', analytics: 'Muhandislik analitikasi', telemetry: 'Oʻsish grafigi, kunlik seriyalar va AI-score telemetriyasi', badges: { title: 'Yutuqlar', clean: 'Clean Code', velocity: 'Tezlik', mentor: 'Mentor signali', architect: 'Arxitektor' }, analyticsLabels: { avgQuality: 'Oʻrtacha sifat', linesVerified: 'Tekshirilgan qatorlar', activeDeadlines: 'Faol muddatlar', skillGrowth: 'Mahorat oʻsish grafigi', skillGrowthSub: 'Muhandislik darajasi dinamikasi', live: 'LIVE', activityHeatmap: 'Faollik xaritasi', heatmapSub: 'Kunlik kodlash seriyasi', less: 'Kam', more: 'Koʻp' }, modulesSection: { title: 'Modullar', openPlan: 'Rejani ochish →', done: 'Tayyor', inProgress: 'Jarayonda', hours: 'soat', tasks: 'topshiriq', noPath: 'Modullarni koʻrish uchun oʻquv yoʻlini tanlang.' }, achievementsSection: { title: 'Yutuqlar', empty: 'Hali yutuqlar yoʻq. Modullarni tugatgandan keyin «Yangilash»ni bosing.' }, certificateSection: { title: 'Sertifikat', description: 'Sertifikat tanlangan yoʻlning barcha modullarini tugatgandan keyin ochiladi.', export: 'Sertifikatni eksport qilish', fallbackName: 'Talaba' } },
    paths: {
      title: 'Oʻquv yoʻlini tanlang', subtitle: 'Yoʻnalish mavzular, topshiriqlar va kelajakdagi sertifikatni belgilaydi.', assessment: 'Daraja testidan oʻtish', roadmap: 'Interaktiv yoʻl xaritasi', hours: 'soat', topics: 'mavzu', deadline: 'Muddat', progress: 'Progress', select: 'Yoʻlni tanlash', footer: 'Ishonchingiz komil boʻlmasa, daraja testidan boshlang.', progressLabel: 'Progress {{progress}}%', moreTopics: '+{{count}}',
      levels: { beginner: 'Boshlovchi', intermediate: 'Oʻrta', advanced: 'Ilgʻor', master: 'Master' },
      tracks: {
        frontend: { title: 'Frontend dasturlash', description: 'HTML, CSS, JavaScript hamda React, Vue va Angular kabi zamonaviy frontend texnologiyalarini oʻzlashtiring' },
        backend: { title: 'Backend dasturlash', description: 'Node.js, Python, Java va C# bilan server tomonini oʻrganing. Ishonchli API va maʻlumotlar bazalarini yarating' },
        mobile: { title: 'Mobil dasturlash', description: 'React Native, Flutter, Swift va Kotlin bilan cross-platform va native mobil ilovalar yarating' },
        'data-science': { title: 'Data Science', description: 'Python, R va SQL orqali data analysis, machine learning va statistik dasturlashga shoʻngʻing' }
      }
    },
    lesson: { notFound: 'Dars topilmadi', chooseLesson: 'Davom etish uchun oʻquv rejasidan dars tanlang.', backToPlan: 'Rejaga qaytish', plan: 'Reja', resources: 'PARA dars resurslari', kicker: '{{hours}} soat oʻqish va amaliyot', showcase: 'Namuna kod', taskSolution: 'Topshiriq va yechim', practiceTasks: '3 ta amaliy topshiriq', instruction: 'Mahalliy topshiriq faylini oching, mashqlarni bajaring va Senior DRM Lead oʻrtacha ballni baholasin.', deadline: 'Aqlli muddat ({{hours}}s): {{time}}', task: 'Topshiriq {{index}}', solveInVSCode: 'VS Codeʻda yechish', verifying: 'Tekshirilmoqda…', verifyTask: 'Topshiriqni tekshirish', accepted: 'Mahorat signali qabul qilindi', iteration: 'Yana bir iteratsiya kerak', reviewComments: 'Review izohlari', terminal: 'verify-terminal', terminalLogs: ['Sintaksis skanerlanmoqda...', 'Clean Code evristikalari qoʻllanmoqda...', 'Senior AI bilan maslahatlashilmoqda...'], average: 'Oʻrtacha AI-score: {{score}}/5', approved: 'Senior DRM Lead davom etishni tasdiqladi.', rule: '4/5 qoidasi faol: oʻrtacha ball kamida 4.0 boʻlguncha topshiriqlarni tekshiring.', completed: 'Tugallandi', complete: 'Tugatish va keyingisini ochish', locked: 'Oʻrtacha 4/5 gacha yopiq', mentor: 'AI Senior Mentor', thinking: 'Oʻylanmoqda...', mentorText: 'Senior DRM Lead uchta topshiriq, arxitektura signallari va davom etishga tayyorgarlikni baholamoqda.', lesson: 'Dars', verdict: 'Xulosa', progressionApproved: 'Davom etish tasdiqlandi', lockedByRule: '4/5 qoidasi bilan yopiq', averageScore: 'Oʻrtacha ball', acrossTasks: '{{score}}/5 — {{count}} topshiriq boʻyicha', paraTip: 'PARA maslahati', paraTipText: 'Tekshiruvdan keyin qayta ishlatiladigan patternlarni Projectsʻdan Resourcesʻga oʻtkazing.', para: { projects: 'Loyihalar', areas: 'Sohalar', resources: 'Resurslar', archives: 'Arxivlar', heading: 'PARA' } },
    learningPlan: { title: 'Oʻquv rejasi', pathLabel: 'Yoʻl', done: 'Tayyor', progress: 'Progress', totalModules: 'Jami modullar', hoursEstimate: 'Soat (taxmin)', level: 'Daraja', modulesTitle: 'Modullar', hours: 'soat', aiScore: 'AI score', requires: 'Kerak', btnDone: 'Tayyor', btnLocked: 'Yopiq', btnStart: 'Boshlash', ruleHint: '4/5 qoidasi: avval {{lessons}} darsida oʻrtacha AI-score ≥ 4.0 oling', changePath: '← Yoʻlni almashtirish', dashboard: 'Dashboard →', levels: { junior: 'Junior', mid: 'Mid', senior: 'Senior', beginner: 'Boshlovchi', intermediate: 'Oʻrta', advanced: 'Ilgʻor', master: 'Master' }, modules: { 'lesson-1-philosophy-career': { title: '1-dars: {{track}} falsafasi va karyera', description: '{{track}} uchun maqsad, sanoat konteksti va karyera yoʻl xaritasini tushuning.' }, 'lesson-2-core-foundations': { title: '{{track}} asosiy fundamentlari', description: '{{stack}} bilan production darajasidagi asoslarni yarating.' }, 'lesson-3-professional-workflow': { title: '{{track}} professional ish jarayoni', description: 'Professional review, refactoring va delivery odatlarini mashq qiling.' } } },
    assessment: { title: 'Bilimlarni baholash', questionOf: 'Savol {{current}} / {{total}}', timeLeft: 'Qolgan vaqt', difficulty: 'Qiyinlik', category: 'Kategoriya', back: 'Orqaga', next: 'Keyingi', finish: 'Tugatish', completed: 'Test tugadi', completedSub: 'Biz darajangizni baholadik va boshlangʻich nuqtani tanladik.', correctAnswers: 'Toʻgʻri javoblar', level: 'Daraja', recommendations: 'Tavsiyalar', strengths: 'Kuchli tomonlar', improve: 'Yaxshilash kerak', goToLearning: 'Oʻqishga oʻtish', levels: { senior: 'Senior', mid: 'Mid', junior: 'Junior' }, descriptions: { senior: 'Yuqori daraja', mid: 'Ishonchli asos', junior: 'Boshlangʻich daraja' }, recs: { senior: 'Murakkab mavzular va real loyihalardan boshlang.', mid: 'Bilimlarni amaliyotda mustahkamlang va murakkabroq topshiriqlarga oʻting.', junior: 'Asoslardan boshlang va muntazam mashq qiling.' }, strengthItems: { goodBase: 'Yaxshi bilim bazasi', logicOk: 'Mantiqiy tafakkur yaxshi', readyToLearn: 'Oʻrganishga tayyor' }, improveItems: { advanced: 'Murakkab mavzular', basics: 'Asoslar', morePractice: 'Koʻproq amaliyot' } }
  } }
} as const

const savedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY) || 'uz'

i18n.use(initReactI18next).init({
  resources,
  lng: savedLanguage,
  fallbackLng: 'uz',
  debug: true,
  interpolation: { escapeValue: false }
})

export default i18n
